[project]
name = "valvestation"
version = "0.0.1"
authors = [
  { name = "Guillermo Reyes" },
  { name = "Ricard Lado" },
]
description = "An HTTP service to control Canonada projects."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = ["canonada", "valvestation"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "canonada==0.6.7",
  "fastapi==0.121.2",
  "python-multipart>=0.0.18",
  "uvicorn==0.35.0",
]

[project.optional-dependencies]
dev = [
  "build>=1.2.2",
  "setuptools>=61.0",
]

[project.scripts]
valvestation = "valvestation.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["valvestation"]

[tool.setuptools.package-data]
"valvestation" = ["templates/config.toml"]
